### ISSUE TITLE
Pool processes error

### ISSUE THREAD

**Issue by rnditdev** [jahongir7174/DeepLabV3#3]
Hello,
I configured a custom dataset, with clases of RGB contents like this:

class1,0,0,0
class2,1.1.1

The dataset seems to be loaded in memory, but just before training, I get the following pool error:

File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 169, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1

This is the whole stacktrace:

. Consider either turning off auto-sharding or switching the auto_shard_policy to DATA to shard this dataset. You can do this by creating a new `tf.data.Options()` object then setting `options.experimental_distribute.auto_shard_policy = AutoShardPolicy.DATA` before applying the options object to the dataset via `dataset.with_options(options)`.
4
2021-06-17 02:15:20.182944: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-06-17 02:15:20.183449: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2199995000 Hz
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jupyter/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/data_utils.py", line 726, in _run
    with closing(self.executor_fn(_SHARED_SEQUENCES)) as executor:
  File "/home/jupyter/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/data_utils.py", line 705, in pool_fn
    initargs=(seqs, None, get_worker_id_queue()))
  File "/opt/conda/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 169, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1

Thank you.

**Comment by rnditdev** [comment]
I've found the answer, I only had 4 processors, and there was the line
generator.start(workers=os.cpu_count() -4)
